global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'yolo_server'
    static_configs:
      - targets: ['yolo_server:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: "mqtt"
    static_configs:
      - targets: ['exporter:9234']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']